// Generated by gencpp from file gopigo_interface/Encoder.msg
// DO NOT EDIT!


#ifndef GOPIGO_INTERFACE_MESSAGE_ENCODER_H
#define GOPIGO_INTERFACE_MESSAGE_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gopigo_interface
{
template <class ContainerAllocator>
struct Encoder_
{
  typedef Encoder_<ContainerAllocator> Type;

  Encoder_()
    : right(0.0)
    , left(0.0)  {
    }
  Encoder_(const ContainerAllocator& _alloc)
    : right(0.0)
    , left(0.0)  {
  (void)_alloc;
    }



   typedef float _right_type;
  _right_type right;

   typedef float _left_type;
  _left_type left;





  typedef boost::shared_ptr< ::gopigo_interface::Encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gopigo_interface::Encoder_<ContainerAllocator> const> ConstPtr;

}; // struct Encoder_

typedef ::gopigo_interface::Encoder_<std::allocator<void> > Encoder;

typedef boost::shared_ptr< ::gopigo_interface::Encoder > EncoderPtr;
typedef boost::shared_ptr< ::gopigo_interface::Encoder const> EncoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gopigo_interface::Encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gopigo_interface::Encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gopigo_interface

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'gopigo_interface': ['/home/salabson/gopigo_ws/src/gopigo_interface/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gopigo_interface::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gopigo_interface::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gopigo_interface::Encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gopigo_interface::Encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gopigo_interface::Encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gopigo_interface::Encoder_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gopigo_interface::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d581e8ae3609f50d2d05ff345e71418";
  }

  static const char* value(const ::gopigo_interface::Encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d581e8ae3609f50ULL;
  static const uint64_t static_value2 = 0xd2d05ff345e71418ULL;
};

template<class ContainerAllocator>
struct DataType< ::gopigo_interface::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gopigo_interface/Encoder";
  }

  static const char* value(const ::gopigo_interface::Encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gopigo_interface::Encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 right\n\
float32 left\n\
\n\
";
  }

  static const char* value(const ::gopigo_interface::Encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gopigo_interface::Encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.right);
      stream.next(m.left);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gopigo_interface::Encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gopigo_interface::Encoder_<ContainerAllocator>& v)
  {
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GOPIGO_INTERFACE_MESSAGE_ENCODER_H
